blog_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired
from flask_wtf.file import FileAllowed


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')
    picture = FileField('Добавить фото к посту', validators=[FileAllowed(['jpg', 'png'])])


class CommentForm(FlaskForm):
    comment = StringField('Комментарий', validators=[DataRequired()])


class LikeForm(FlaskForm):
    submit = SubmitField('Создать')

blog_app/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from blog_app import db
from blog_app.models import Post, Comment, Like
from blog_app.posts.forms import PostForm, CommentForm, LikeForm
from blog_app.users.utils import save_picture

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    picture_name = None
    if form.validate_on_submit():
        if form.picture.data:
            picture_name = save_picture(form.picture.data)
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user, image_file=picture_name)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html',
                           title='Новый пост', form=form, image_file=picture_name, legend='Новый пост')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    like_form = LikeForm()
    like_count = Like.query.filter_by(post_id=post_id).count()
    if form.validate_on_submit():
        comment = Comment(text_comment=form.comment.data, post_id=post_id,
                          username=current_user.username)
        db.session.add(comment)
        db.session.commit()
        flash('Ваш комментарий добавлен!')
        return redirect(f'/post/{post_id}')

    return render_template('post.html', title=post.title, post=post, like_form=like_form,
                           like_count=like_count, form=form)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            post.image_file = picture_file
        db.session.commit()
        flash('Ваш пост обновлен!')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        image_file = url_for('static', filename='profile_image/' + post.image_file)
    return render_template('create_post.html', title='Обновление поста', form=form, image_file=image_file,
                           legend='Обновление поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!')
    return redirect(url_for('posts.allpost'))


@posts.route("/comment/<int:comment_id>/delete", methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.username != current_user.username:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Ваш комментарий был удален!')
    return redirect(url_for('posts.post', post_id=comment.post_id))


@posts.route('/post/<string:post_id>/like', methods=('POST',))
@login_required
def like_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author == current_user:
        flash('Вы не можете поставить себе лайк')
    elif Like.query.filter_by(user_id=current_user.id, post_id=post_id).count():
        Like.query.filter_by(user_id=current_user.id, post_id=post_id).delete()
        db.session.commit()
        flash('Вам не понравился этот пост.')
    else:
        like = Like(user_id=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()
        flash('Вам нравится этот пост.')

    return redirect(url_for('posts.post', post_id=post_id))

blog_app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blog_app import db, bcrypt
from blog_app.models import User, Post
from blog_app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm

from blog_app.users.utils import save_picture

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана! Теперь вы можете войти в систему')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Регистрация', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту и пароль')
    return render_template('login.html', title='Авторизация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user) \
            .order_by(Post.date_posted.desc()) \
            .paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_image/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, posts=posts, user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

blog_app/templates/account.html
{% extends "layout.html" %}


{% block content %}

<div class="media">
    <img src="{{ image_file }}">
    <p>Имя пользователя: {{ current_user.username }}</p>
    <p>Адрес электронной почты: {{ current_user.email }}</p>
</div>

<form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset>
        <legend>Аккаунт пользователя</legend>
        {{ form.username.label }}
        {% if form.username.errors %}
        {{ form.username }}
        {% for error in form.username.errors %}
        {{ error }}
        {% endfor %}
        {% else %}
        {{ form.username }}
        {% endif %}
        <div class="form-group">
            {{ form.email.label }}
            {% if form.email.errors %}
            {{ form.email }}
            {% for error in form.email.errors %}
            {{ error }}
            {% endfor %}
            {% else %}
            {{ form.email }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.picture.label() }}
            {{ form.picture }}
            {% if form.picture.errors %}
            {% for error in form.picture.errors %}
            {{ error }}
            {% endfor %}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group">
        Кнопка {{ form.submit }} аккаунт пользователя
    </div>
</form>


{% endblock content %}

blog_app/templates/allpost.html
{% extends "layout.html" %}

{% block content %}
{% for post in posts.items %}
<div class="container">
    <br>
    <img src="{{ url_for('static', filename='profile_image/' + post.author.image_file) }}">
    </br>
    <small>Автор поста: </small><a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
    <div class="card">
        <small>Название поста: </small><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
        <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
        <p><small>Текст поста: </small> {{ post.content }}</p>
    </div>
</div>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
{% else %}
<a href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}

{% endif %}
{% endfor %}
{% endblock content %}

blog_app/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

<form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend>{{ legend }}</legend>
        {{ form.title.label }}
        {% if form.title.errors %}
        {{ form.title}}
        {% for error in form.title.errors %}
        {{ error }}
        {% endfor %}
        {% else %}
        {{ form.title }}
        {% endif %}
        <div class="form-group">
            {{ form.content.label }}
            {% if form.content.errors %}
            {{ form.content }}
            {% for error in form.content.errors %}
            {{ error }}
            {% endfor %}
            {% else %}
            {{ form.content }}
            {% endif %}
            <div class="form-group">
                {{ form.picture.label }}
                {{ form.picture }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                {{ error }}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit }}
    </div>
</form>

{% endblock content %}

blog_app/templates/home.html
{% extends "layout.html" %}


{% block content %}
<div class="heading">
    <h1>ДОБРО ПОЖАЛОВАТЬ В МОЙ БЛОГ!</h1>
</div>

<p>Тут и только тут вы можете размещать свои посты на разные темы</p>


{% endblock content %}

blog_app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    {% if title %}
    <title>Blog - {{ title }}</title>
    {% else %}
    <title>Blog</title>
    {% endif %}
</head>
<body>
{% if current_user.is_authenticated %}
<h4> Привет, {{ current_user.username }}!</h4>
<a href="{{ url_for('posts.new_post') }}">Новая запись</a>
<a href="{{ url_for('users.account') }}">Профиль</a>
<a href="{{ url_for('posts.allpost') }}">Записи блога</a>
<a href="{{ url_for('users.logout') }}">Выйти</a>
{% else %}
<a href="{{ url_for('users.register') }}">Зарегистрироваться</a>
<a href="{{ url_for('users.login') }}">Войти</a>
{% endif %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
{{ message }}
{% endfor %}
{% endif %}
{% endwith %}

{% block content %}{% endblock %}
</body>
</html>

blog_app/templates/login.html
{% extends "layout.html" %}
{% block content %}

<form method="POST" action="">
    {{ form.hidden_tag() }}
    <legend>Авторизация</legend>
    {{ form.email.label }}
    {% if form.email.errors %}
    {{ form.email }}

    {% for error in form.email.errors %}
    {{ error }}
    {% endfor %}

    {% else %}
    {{ form.email }}
    {% endif %}
    <div class="form-group">
        {{ form.password.label }}
        {% if form.password.errors %}
        {{ form.password }}
        {% for error in form.password.errors %}
        {{ error }}
        {% endfor %}
        {% else %}
        {{ form.password }}
        {% endif %}
    </div>
    {{ form.remember }}
    {{ form.remember.label }}
    <div class="form-group">
        {{ form.submit }}
    </div>
    <small>
        Нужен аккаунт? <a href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
    </small>
</form>

{% endblock content %}

blog_app/templates/post.html
{% extends "layout.html" %}


{% block content %}
<br>
<img style="width: 100px;" src="{{ url_for('static', filename='profile_image/' + post.author.image_file) }}">
</br>
<small>Автор поста: </small><a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
<h4><small>Заголовок поста: </small>{{ post.title }}</h4>
<small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
{% if post.image_file %}
<div class="form-group">
   <p>Изображение к посту </p><img   src="{{ url_for('static', filename='profile_image/' + post.image_file) }}">
</div>
{% endif %}

<p>Текст поста: {{ post.content }}</p>
<form action="{{ url_for('posts.like_post', post_id=post.id) }}" method="post">
  Поставь лайк))){{ like_form.hidden_tag() }}
     <button type="submit">
       <img style="width: 32px;" src="{{ url_for('static',filename='images/like.svg') }}" alt="...">
       {{ like_count if like_count > 0 }}
     </button>
</form>

{% if post.author == current_user %}
{% if post.author == current_user %}
<a href="{{url_for('posts.update_post', post_id=post.id) }}">Обновить пост</a>
{% endif %}
{% endif %}
<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
    <input type="submit" value="Удалить пост">
</form>

{% if post.comments %}
<h4>Комментарии: </h4>
{% for comment in post.comments | reverse %}
<p><small>Текст комментария: </small>{{ comment.text_comment }}</p>
<p><small>Автор: {{ comment.username }}</small>
    <small>Дата: {{ comment.date_comment.strftime('%A, %d %B %Y %I:%M %p') }}</small></p>
{% if comment.username == current_user.username %}
<form action="{{ url_for('posts.delete_comment', comment_id=comment.id) }}" method="POST">
    <input type="submit" value="Удалить комментарий">
</form>
{% endif %}
{% endfor %}
{% endif %}

<h4>Оставьте комментарий</h4>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <span></span><textarea class="contact" name="comment" rows="5"></textarea>
    {% if form.comment.errors %}
    {% for error in form.comment.errors %}
    {{ error }}
    {% endfor %}
    {% endif %}
    <input class="submit" type="submit" name="submit" value="Сохранить">
</form>
{% endblock content %}

blog_app/templates/register.html
{% extends "layout.html" %}
{% block content %}

<form method="POST" action="">
    {{ form.hidden_tag() }}

    <h3>Регистрация</h3>

    {{ form.username.label }}
    {% if form.username.errors %}
    {{ form.username }}
    {% for error in form.username.errors %}
    {{ error }}
    {% endfor %}
    {% else %}
    {{ form.username }}
    {% endif %}

    <div class="form-group">
        {{ form.email.label }}
        {% if form.email.errors %}
        {{ form.email }}
        {% for error in form.email.errors %}
        {{ error }}
        {% endfor %}
        {% else %}
        {{ form.email }}
        {% endif %}
    </div>

    <div class="form-group">
        {{ form.password.label }}
        {% if form.password.errors %}
        {{ form.password }}
        {% for error in form.password.errors %}
        {{ error }}
        {% endfor %}
        {% else %}
        {{ form.password }}
        {% endif %}
    </div>

    <div class="form-group">
        {{ form.confirm_password.label }}
        {% if form.confirm_password.errors %}
        {{ form.confirm_password }}
        {% for error in form.confirm_password.errors %}
        {{ error }}
        {% endfor %}
        {% else %}
        {{ form.confirm_password }}
        {% endif %}
    </div>

    <div class="form-group">
        {{ form.submit }}
    </div>
</form>

{% endblock content %}

blog_app/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
<h1>Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<img src="{{ url_for('static', filename='profile_image/' + post.author.image_file) }}">
<p>Имя пользователя <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username
    }}</a></p>
<h4>Название поста: <a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
<small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
<p>Запись поста: {{ post.content }}</p>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
{% else %}
<a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}
{% endif %}
{% endfor %}
{% endblock content %}